// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOVDL3dGR2LVN82SBKrd4MjrMvNRkGfSI',
    appId: '1:343726077774:web:916ba4a634595918db901f',
    messagingSenderId: '343726077774',
    projectId: 'aranton-d1l-project',
    authDomain: 'aranton-d1l-project.firebaseapp.com',
    storageBucket: 'aranton-d1l-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3iXEz9CUoiGRCtth-aaA9HRmGVwSFjk',
    appId: '1:343726077774:android:2844d1c1a8fe7cccdb901f',
    messagingSenderId: '343726077774',
    projectId: 'aranton-d1l-project',
    storageBucket: 'aranton-d1l-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUHP1TdlWjRqkQjdM9Xj3ltcxhhW8OqZo',
    appId: '1:343726077774:ios:cc2fd25855532706db901f',
    messagingSenderId: '343726077774',
    projectId: 'aranton-d1l-project',
    storageBucket: 'aranton-d1l-project.appspot.com',
    iosClientId: '343726077774-8m8a8bi0s06dfph1iv3bqk0gbb638t5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAranton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUHP1TdlWjRqkQjdM9Xj3ltcxhhW8OqZo',
    appId: '1:343726077774:ios:cc2fd25855532706db901f',
    messagingSenderId: '343726077774',
    projectId: 'aranton-d1l-project',
    storageBucket: 'aranton-d1l-project.appspot.com',
    iosClientId: '343726077774-8m8a8bi0s06dfph1iv3bqk0gbb638t5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAranton',
  );
}
